## PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1


In [3]:
# Check that MPS is available
if not torch.backends.mps.is_available():
    if not torch.backends.mps.is_built():
        print("MPS not available because the current PyTorch install was not "
              "built with MPS enabled.")
    else:
        print("MPS not available because the current MacOS version is not 12.3+ "
              "and/or you do not have an MPS-enabled device on this machine.")

else:
    print("MPS acceleration is available")
    # mps_device = torch.device("mps")
    # Move your model to mps just like any other device
    # model = YourFavoriteNet()
    # model.to(mps_device)

    # Now every call runs on the GPU
    # pred = model(x)


MPS acceleration is available


## Introduction to tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim)

# Get back python int
scalar.item()

tensor(7)
0


7

In [5]:
# Vector
vector = torch.tensor([7, 7])
# note that this is a 1 dimensional vector
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [11]:
# We have a 2x1 element
vector.shape

torch.Size([2])

In [23]:
# MATRIX
MATRIX = torch.tensor([[7, 8, 9],
                       [9, 10, 11],
                      [9, 10, 11]])
MATRIX

tensor([[ 7,  8,  9],
        [ 9, 10, 11],
        [ 9, 10, 11]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([3, 3])

In [16]:
# 0-th dimension
print(MATRIX[0].shape)

# 1-st dimension
print(MATRIX[1])

torch.Size([2])
tensor([ 9, 10])


In [26]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                      [3, 6, 9], 
                      [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [27]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [40]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
# You can also do torch.rand(size=(3, 4))
random_tensor

tensor([[0.9886, 0.9730, 0.5639, 0.3581],
        [0.5523, 0.6588, 0.1288, 0.8259],
        [0.4778, 0.6273, 0.8581, 0.9750]])

In [36]:
random_tensor.ndim

2

In [38]:
random_tensor.shape

torch.Size([3, 4])

In [41]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [52]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
mask_tensor = torch.zeros(size=(3,1))
mask_tensor

tensor([[0.],
        [0.],
        [0.]])

In [62]:
mask_tensor*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [66]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [69]:
ones.dtype 

torch.float32

### Creating a range of tensors and tensors-like

In [71]:
# Use torch.range()
torch.range(0, 10)

/var/folders/s9/c5_nm34x0vl70w912_lld2vw0000gn/T/ipykernel_35946/1840815090.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [73]:
torch.__version__

'2.0.1'

In [78]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
torch.arange(start=1, end=10, step=2) # end is not included

tensor([1, 3, 5, 7, 9])

In [86]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [108]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                                device=None, # cpu (default) or mps (for macs) or cuda (for gpus) 
                                requires_grad=False) # whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [110]:
float_32_tensor.dtype

torch.float32

In [112]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [117]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [124]:
int_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [125]:
float_32_tensor * int_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [131]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4785, 0.9216, 0.2167, 0.0989],
        [0.5624, 0.1264, 0.9848, 0.4549],
        [0.5788, 0.8020, 0.5880, 0.9379]])

In [137]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.4785, 0.9216, 0.2167, 0.0989],
        [0.5624, 0.1264, 0.9848, 0.4549],
        [0.5788, 0.8020, 0.5880, 0.9379]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [149]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [151]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [153]:
# Substract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [161]:
# Try out PyTorch inbuilt functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10)) 

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3, 2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @(2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [166]:
# Element wise multiplication
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [170]:
# Matrix multiplication
torch.matmul(tensor, tensor) # 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [172]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.38 ms, sys: 690 µs, total: 2.07 ms
Wall time: 1.64 ms


tensor(14)

In [176]:
%%time
torch.matmul(tensor, tensor) # same as tensor @ tensor

CPU times: user 316 µs, sys: 208 µs, total: 524 µs
Wall time: 372 µs


tensor(14)

### One of the most common errors in deep lerarning: shape errors

Reference: http://matrixmultiplication.xyz/

In [181]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
print(tensor_A.shape)
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
print(tensor_B.shape)
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

torch.Size([3, 2])
torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**
A transpose switches the axes or dimensions of a given tensor.

In [187]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [190]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [194]:
torch.mm(tensor_B, tensor_B.T)

tensor([[149, 166, 183],
        [166, 185, 204],
        [183, 204, 225]])

In [197]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [205]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [202]:
# Find the min
torch.min(x), x.min

(tensor(0), <function Tensor.min>)

In [203]:
# Find the max
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [210]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [212]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [219]:
# Find the position in tensor that has the min/max value
# This returns the index position of target tensor where min/max value occurs
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [220]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimentions permuted (swapped) in a certain way

In [244]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [233]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [234]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [243]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [254]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [255]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [258]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [271]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [277]:
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.shape, x_squeezed, x_squeezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [283]:
x_squeezed.unsqueeze(dim=1), x_squeezed.unsqueeze(dim=1).shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [285]:
# Permute the dimensions
x = torch.randn(2, 3, 5)
print(x)
print(x.shape)
print(torch.permute(x, (2, 0, 1)))
print(torch.permute(x, (2, 0, 1)).shape)


tensor([[[ 0.0104,  0.4783,  0.5157, -0.0830, -0.6526],
         [ 0.7018, -0.1801, -0.6713, -0.7977, -1.3376],
         [-0.2163, -1.4021,  1.1246, -0.5250,  1.0711]],

        [[ 0.2214, -0.2374,  0.7189,  0.4869,  1.8059],
         [ 0.9074, -1.4215, -0.3504,  0.5282, -0.0888],
         [ 0.5158,  1.0846, -0.2615, -0.1300,  0.5549]]])
torch.Size([2, 3, 5])
tensor([[[ 0.0104,  0.7018, -0.2163],
         [ 0.2214,  0.9074,  0.5158]],

        [[ 0.4783, -0.1801, -1.4021],
         [-0.2374, -1.4215,  1.0846]],

        [[ 0.5157, -0.6713,  1.1246],
         [ 0.7189, -0.3504, -0.2615]],

        [[-0.0830, -0.7977, -0.5250],
         [ 0.4869,  0.5282, -0.1300]],

        [[-0.6526, -1.3376,  1.0711],
         [ 1.8059, -0.0888,  0.5549]]])
torch.Size([5, 2, 3])


In [294]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
print(x_original.shape)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (2, 0, 1))# [color_channels, height, width]
print(x_permuted.shape)

print(x_original.permute(2, 0, 1).shape) # shifts axis 1->1, 1->2, 2->0

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])
torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy.

In [298]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [302]:
# Let's index on our new tensor
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [304]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0][0].shape # this is same as x[0,0]

(tensor([1, 2, 3]), torch.Size([3]))

In [310]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0][0][0].ndim, x[0][0][0].shape, x[0][0][0].item() 

(tensor(1), 0, torch.Size([]), 1)

In [326]:
# You can also use ":" to select "all" of a target dimension
x[:, :, 0]


tensor([[1, 4, 7]])

In [328]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [330]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [333]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [339]:
# index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [350]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [344]:
array.dtype

dtype('float64')

In [347]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [351]:
# But we can always do as follows:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [354]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [358]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_array = tensor.numpy()
tensor, type(tensor), numpy_array, type(numpy_array)

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.Tensor,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 numpy.ndarray)

In [360]:
# Change the tensor, what happens to `numpy_array`?
tensor = tensor + 1
tensor, numpy_array

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what a random seed does is "flavour" the randomness.

In [369]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3064, 0.1361, 0.6949, 0.3499],
        [0.0385, 0.1982, 0.8112, 0.4088],
        [0.8399, 0.9727, 0.8315, 0.8793]])
tensor([[0.8436, 0.4455, 0.5673, 0.4110],
        [0.4841, 0.7677, 0.8522, 0.4263],
        [0.5958, 0.0340, 0.1283, 0.7283]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [375]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Extra resources on reproducibility
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory

### 1. Getting a GPU

1. Easiest - use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options (See this post for options: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/)
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3, PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer PyTorch setup documentation

### 2. Check for GPU access with PyTorch

In [384]:
# Check for GPU access with PyTorch
import torch
print(torch.cuda.is_available())
print(torch.backends.mps.is_available())

False
True


In [386]:
# Setup device agnostic code
# device = "cuda" if torch.cuda.is_available() else "cpu"

device = "cpu"
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"

device

'mps'

In [390]:
# Count the number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [393]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [395]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

### 4. Moving tensors back to the CPU

In [397]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [410]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [412]:
tensor_on_gpu * tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!